config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions'}
  get 'welcome/index'

  resources :articles do
  	resources :comments
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "photos#index"
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	  has_many :comments, dependent: :destroy
	  validates :title, presence: true,
                    length: { minimum: 1 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/photo.rb
class Photo < ApplicationRecord
  #Mounts paperclip image
  has_attached_file :image, :styles => { :thumb => ['300x300#', :png] } 
  #This validates the type of file uploaded. According to this, only images are allowed.
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/	
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
end

app/models/upload.rb
class Upload < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	

	def index
		@articles = Article.all
	end


	def show
		@article = Article.find(params[:id])
	end


	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
  		@article = Article.new(article_params)
 		
  		if@article.save
  		redirect_to @article
  		else
  			render 'new'	
  		end
	end

	def update
  		@article = Article.find(params[:id])
 
  		if @article.update(article_params)
    		redirect_to @article
  		else
    		render 'edit'
  		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

private
  	def article_params
    	params.require(:article).permit(:title, :text)
  	end	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
	
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end  
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end	
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

 #Index action, photos gets listed in the order at which they were created
 def index
  @photos = Photo.order('created_at')
 end

 #New action for creating a new photo
 def new
  @photo = Photo.new
 end

 #Create action ensures that submitted photo gets created if it meets the requirements
 def create
  @photo = Photo.new(photo_params)
  if @photo.save
   flash[:notice] = "Successfully added new photo!"
   redirect_to photos_url
  else
   flash[:alert] = "Error adding new photo!"
   render :new
  end
 end
 




   #Destroy action for deleting an already uploaded image
  def destroy
  @photo = Photo.find(params[:id])
    if @photo.destroy
      flash[:notice] = "Successfully deleted photo!"
      redirect_to photos_url
    else
      flash[:alert] = "Error deleting photo!"
    end
  end

 private

 #Permitted parameters when creating a photo. This is used for security reasons.
 def photo_params
  params.require(:photo).permit(:title, :image)
 end

end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/winkels_helper.rb
module WinkelsHelper
end

app/views/photos/index.html.erb
<div class="container">
<div class="col-sm-12">
<div class="panel panel-default">
  <div class="panel-heading">Winkels overzicht</div>
  <div class="panel-body"><%= link_to 'New Winkel', new_photo_path %></div>
</div>
</div>  
  <div class="row">
    <div class="col-sm-12">
    <% @photos.each do |photo| %>
    <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading"><%= photo.title %></div>
      <div class="panel-body"><%= link_to image_tag(photo.image.url(:thumb), class: 'media-object'), photo.image.url(:thumb), target: '_blank' %></div>
      <div class="panel-footer">
        <%= link_to 'Bekijken', photo_path(photo), class: 'btn btn-primary' %> <%= link_to 'Remove', photo_path(photo), class: 'btn btn-primary', method: :delete, data: {confirm: 'Are you sure?'} %>
      </div>
    </div>
    </div>
    <% end %>
  </div>
  </div>
</div>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Winkel</h1></div>

<%= form_for @photo, html: { multipart: true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
      </h2>
      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
        <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/welcome/index.html.erb
<div class="container">    
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading">Folder 1</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Dit is een folder</div>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-primary">
        <div class="panel-heading">Folder 2</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Dit is een folder</div>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-primary">
        <div class="panel-heading">Folder 3</div>
        <div class="panel-body"><img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Dit is een folder</div>
      </div>
    </div>
  </div>
</div>